name: Fuzz testing with echidna

on: [push, pull_request]
jobs:
  echidna:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - BondingV2

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Install solc 0.8.16
        run: |
          solc-select install 0.8.16
          solc-select use 0.8.16

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Install Echidna
        run: |
          sudo wget -O /tmp/echidna-test.tar.gz https://github.com/crytic/echidna/releases/download/v2.0.3/echidna-test-2.0.3-Ubuntu-18.04.tar.gz
          sudo tar -xf /tmp/echidna-test.tar.gz -C /usr/bin
          sudo chmod +x /usr/bin/echidna-test

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn workspace @ubiquity/contracts forge install

      - name: Run ${{ matrix.testName }}
        run: |
          cd packages/contracts
          echidna-test . --contract ${{ matrix.testName }} --config echidna.config.yml
